### ISSUE TITLE
Help for GSRC dataset

### ISSUE THREAD

**Issue by wyclike** [AugustUnderground/pygsrc#1]
I couldn't download the GSRC-benchmark from the url:http://vlsicad.eecs.umich.edu/BK/GSRCbench/.
Could you help me for this? Could you send me the GSRC-benchmark from email? Thank you very much!

**Comment by AugustUnderground** [comment]
It seems like the website is down. I'm not affiliated with the University of Michigan, so I can't tell you what's wrong, or how long it's going to take them to get back up.

Here is what I had downloaded a few months ago for testing: [gsrc.tar.gz](https://github.com/AugustUnderground/pygsrc/files/15392437/gsrc.tar.gz)

I'll put it here instead of sending it by email, in case someone else encounters the same problem.

**Comment by wyclike** [comment]
> It seems like the website is down. I'm not affiliated with the University of Michigan, so I can't tell you what's wrong, or how long it's going to take them to get back up.
> 
> Here is what I had downloaded a few months ago for testing: [gsrc.tar.gz](https://github.com/AugustUnderground/pygsrc/files/15392437/gsrc.tar.gz)
> 
> I'll put it here instead of sending it by email, in case someone else encounters the same problem.

Thank you very much！

**Comment by AugustUnderground** [comment]
If that solved your issue, I'll close this.
