### ISSUE TITLE
What is this dataset about?

### ISSUE THREAD

**Issue by ogencoglu** [AugustUnderground/pygsrc#4]
Can you explain what is the dataset about?

**Comment by AugustUnderground** [comment]
It is an old benchmark for IC floorplanning algorithms. Many people use it for their own implementations to compare against other state of the art methods. You can download it from [umich](http://vlsicad.eecs.umich.edu/BK/GSRCbench/). Each problem is organized into a `block` file containing all the cells that must be considered, a `pl` file for the initial placement, and a `net` file for the connectivity among the blocks, if you want to consider routing. `HARD` blocks are fixed in size, but `SOFT` blocks may have some alternative aspect ratios.

Are you doing research in IC design and/or EDA?

**Comment by ogencoglu** [comment]
OK thanks for the clarification.
